#!/bin/bash

function copy()
{
	cp -f $1 ${1#"/"}
}

function copy_bin()
{
	path=$(which $1)
	copy $path
	libs=$(ldd $path | awk '$0 ~ "linux-vdso" {next} $0 ~ "=>" {print $3; next} {print $1}')
	for i in $libs ; do
		copy $i
	done
}

mkdir $1
cd $1
mkdir -p {bin,sbin,lib64,etc,usr/lib64,usr/bin,usr/share/terminfo/x}
cp /usr/share/terminfo/x/{xterm,xterm-256color} usr/share/terminfo/x

echo "= CLADDER CONTAINER =

  $1
" > etc/motd

echo "#!/bin/sh

cat /etc/motd

/bin/bash" > sbin/init
chmod +x sbin/init

copy "/etc/resolv.conf"
copy "/lib64/libnss_files.so.2"
copy "/lib64/libnss_dns.so.2"
echo "root:x:0:0:root:/root:/bin/bash" > etc/passwd
echo "
passwd:      compat files
shadow:      compat files
group:       compat files

hosts:       files dns
networks:    files dns

services:    db files
protocols:   db files
rpc:         db files
ethers:      db files
netmasks:    files
netgroup:    files
bootparams:  files

automount:   files
aliases:     files" > etc/nsswitch.conf
copy_bin "curl"
copy_bin "bash"
copy_bin "cat"
copy_bin "echo"
copy_bin "sh"
copy_bin "ls"
copy_bin "tree"
copy_bin "du"
copy_bin "ping"
copy_bin "df"
copy_bin "htop"
copy_bin "strace"
